spring:
  datasource:
    url: jdbc:h2:file:./db/alarm;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: lg@xxb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update